PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS devices(id INTEGER PRIMARY KEY AUTOINCREMENT,brand TEXT NOT NULL,model TEXT NOT NULL,variant TEXT,platform TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS repair_cases(id INTEGER PRIMARY KEY AUTOINCREMENT,device_id INTEGER NOT NULL,symptom TEXT NOT NULL,complaint TEXT,observation TEXT,diagnosis TEXT,action TEXT,result TEXT,verification TEXT,status TEXT NOT NULL DEFAULT 'DRAFT',trust_level TEXT NOT NULL DEFAULT 'COMMUNITY_REPORT',source_url TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(device_id) REFERENCES devices(id));
CREATE TABLE IF NOT EXISTS rules(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,symptom TEXT NOT NULL,observation TEXT,condition_key TEXT,condition_value TEXT,fault_group TEXT,next_step TEXT NOT NULL,rationale TEXT,priority INTEGER NOT NULL DEFAULT 100,status TEXT NOT NULL DEFAULT 'ACTIVE',trust_level TEXT NOT NULL DEFAULT 'VERIFIED');
CREATE TABLE IF NOT EXISTS EXT_REFERENCES(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,url TEXT NOT NULL,source_type TEXT NOT NULL,credibility TEXT NOT NULL DEFAULT 'UNVERIFIED',notes TEXT);
CREATE INDEX IF NOT EXISTS idx_rules_symptom ON rules(symptom);
CREATE INDEX IF NOT EXISTS idx_cases_device_symptom ON repair_cases(device_id,symptom);
